name: dnotify
description: dahliaOS notifications backend
version: 1.0.0-alpha.1
homepage: https://dahliaos.io/

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
